#!/bin/bash

make="${MAKE:-make}"

makesample=true
if [[ $1 == "--nosample" ]]
then
	makesample=false
	shift
fi

cd lib
$make $1 $2 || exit

cd usb
$make $1 $2 || exit
cd ..

cd input
$make $1 $2 || exit
cd ..

cd fs
$make $1 $2 || exit

cd fat
$make $1 $2 || exit
cd ..

cd ..

cd sched
$make $1 $2 || exit
cd ..

cd net
$make $1 $2 || exit
cd ..

cd ..

# added by mcarter for tinybasic 26-Feb-2020
cd addon

cd SDCard
$make $1 $2 || exit
cd ..

cd fatfs
$make $1 $2 || exit
cd ..

cd ..
# end of mcarter additions

if [[ $makesample == true ]]
then
	cd sample
	./makelatest $1 $2 || exit
	cd ..
fi
