#!/usr/bin/env bash

function print_help {
cat <<EOF
Description here
etc
EOF
}
 

case $1 in
    h) print_help ; exit ;;
esac


EXE=/home/pi/Documents/qemu/builds/arm-softmmu/qemu-system-arm
IMG=~/repos/circle/sample/08*/kernel7.img
IMG=kernel7.img
ls $IMG
$EXE -M raspi2 -bios  $IMG  -usbdevice keyboard
